name: Docker Image CI for GHCR
on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm ci
      - name: run the unit tests
        run: npm test
      - name: Publish the image to github container registry
        run: |
          docker login --username josephtham --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/josephtham/arithmetic-service:1 --file Dockerfile .
          docker push ghcr.io/josephtham/arithmetic-service:1
      - name: Publish the image to azure container registry
        run: |
          docker login --username josephthampracticum7 --password ${{secrets.AZURE_CONTAINER_REGISTRY}} josephthampracticum7.azurecr.io
          docker tag ghcr.io/josephtham/arithmetic-service:1  josephthampracticum7.azurecr.io/arithmetic-service:1
          docker push josephthampracticum7.azurecr.io/arithmetic-service:1